apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssi
  template:
    metadata:
      labels:
        app: ssi
    spec:
      containers:
        - name: ssi-server
          image: ghcr.io/chonnisat/ssi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-service
spec:
  selector:
    app: ssi
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
