apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff
  template:
    metadata:
      labels:
        app: staff
    spec:
      containers:
        - name: staff-server
          image: ghcr.io/chonnisat/ssi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: staff-service
  labels:
    app: staff-service
spec:
  selector:
    app: staff
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
